output: web

title: title
baseurl: ""
url: ""

topnav_title: documentation

site_title: doc_site_title

# Build settings
markdown: kramdown

defaults:
    - scope:
          path: ""
          type: "pages"
      values:
          layout: "page"
          comments: true
          search: true
          sidebar: home_sidebar
          topnav: topnav

plugins:
    - jekyll-toc

sidebars:
    - home_sidebar
    - mydoc_sidebar
